service: FHZ-Koa-Serverless-App

frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev

functions: ${file(./serverless/functions.yml)}
